In [2]:
%pip install geopandas

Collecting geopandas
  Using cached geopandas-1.1.4-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy>=1.24 in c:\users\hp\anaconda3\lib\site-packages (from geopandas) (2.3.5)
Collecting pyogrio>=0.7.2 (from geopandas)
  Using cached pyogrio-0.13.0-cp311-abi3-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\lib\site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from geopandas) (2.3.3)
Collecting pyproj>=3.5.0 (from geopandas)
  Using cached pyproj-3.8.0-cp313-cp313-win_amd64.whl.metadata (40 kB)
Requirement already satisfied: shapely>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\hp\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.11.12)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Using cached geopandas-1.1.4-py3-none-any.whl (343 kB)
Using cached pyogrio-0.13.0-cp311-abi3-win_amd64.whl (23.8 MB)
Using cached pyproj-3.8.0-cp313-cp313-win_amd64.whl (6.7 MB)
Installing collected packages: pyproj, pyogrio, geopandas

   ---------------------------------------- 0/3 [pyproj]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   ------------- -------------------------- 1/3 [pyogrio]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   -------------------------- ------------- 2/3 [geopandas]
   ---------------------------------------- 3/3 [geopandas]

Successfully installed geopandas-1.1.4 pyogrio-0.13.0 pyproj-3.8.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
import geopandas as gpd

file_path = r"C:\Users\HP\OneDrive\Udyam360\data\warud_places.geojson"

gdf = gpd.read_file(file_path)

print("Number of records:", len(gdf))
print("Number of columns:", len(gdf.columns))

gdf.head()

Number of records: 200
Number of columns: 15

,id,categories,confidence,websites,emails,socials,phones,brand,addresses,names,sources,basic_category,taxonomy,version,geometry
0,bbe4bc24-1a3d-4d40-8ace-be407c8662c8,"{'primary': 'auto_parts_and_supply_store', 'al...",0.319494,None,None,[https://www.facebook.com/606473572895874],None,"{'wikidata': None, 'names': {'primary': None, ...","[{'freeform': 'Warud Road', 'locality': 'Warud...","{'primary': 'Pintu Motors', 'common': None, 'r...","[{'property': '', 'dataset': 'meta', 'license'...",vehicle_parts_store,"{'primary': 'auto_parts_store', 'hierarchy': [...",11,POINT (78.27744 21.47581)
1,2c3391d1-78fa-4a2a-a4ab-f82c12fc56cb,"{'primary': 'educational_services', 'alternate...",0.396972,None,None,[https://www.facebook.com/893333997687424],[+919021217363],"{'wikidata': None, 'names': {'primary': None, ...","[{'freeform': 'Pardi Rd', 'locality': 'Warud',...","{'primary': 'Thor Guidance Career Point', 'com...","[{'property': '', 'dataset': 'meta', 'license'...",educational_service,"{'primary': 'educational_service', 'hierarchy'...",10,POINT (78.27624 21.47176)
2,62ff2063-969d-4c2c-80e8-d9347a157d0c,"{'primary': 'train_station', 'alternate': ['tr...",0.805240,None,None,[https://www.facebook.com/2044796279081838],None,"{'wikidata': None, 'names': {'primary': None, ...","[{'freeform': None, 'locality': 'Warud', 'post...",{'primary': 'Warud Orange City railway station...,"[{'property': '', 'dataset': 'meta', 'license'...",train_station,"{'primary': 'train_station', 'hierarchy': ['tr...",1,POINT (78.27616 21.45872)
3,6b5cb467-e79f-49a0-b66e-c45c72daee8c,"{'primary': 'hindu_temple', 'alternate': None}",0.561847,None,None,[https://www.facebook.com/153445861956810],None,"{'wikidata': None, 'names': {'primary': None, ...","[{'freeform': None, 'locality': 'Warud', 'post...","{'primary': 'Sai Mandir', 'common': None, 'rul...","[{'property': '', 'dataset': 'meta', 'license'...",hindu_place_of_worship,"{'primary': 'hindu_place_of_worship', 'hierarc...",8,POINT (78.28139 21.46639)
4,6ff16c9a-35b7-4a0f-b4e2-47901d117362,"{'primary': 'party_and_event_planning', 'alter...",0.682641,None,None,[https://www.facebook.com/103875957919357],[+919156177600],"{'wikidata': None, 'names': {'primary': None, ...","[{'freeform': 'Amravati, Sh-248, Nagpur Warud ...",{'primary': 'Late Shri Marutrao Kherade Sabhag...,"[{'property': '', 'dataset': 'meta', 'license'...",event_or_party_service,"{'primary': 'party_and_event_planning', 'hiera...",3,POINT (78.27565 21.46604)

In [4]:
gdf.columns.tolist()

['id',
 'categories',
 'confidence',
 'websites',
 'emails',
 'socials',
 'phones',
 'brand',
 'addresses',
 'names',
 'sources',
 'basic_category',
 'taxonomy',
 'version',
 'geometry']

In [5]:
print("Basic categories:")
print(gdf["basic_category"].value_counts())

Basic categories:
basic_category
bank_or_credit_union         15
hospital                     12
fashion_and_apparel_store    10
shopping                      9
restaurant                    7
                             ..
printing_service              1
movie_theater                 1
police_station                1
specialty_school              1
religious_organization        1
Name: count, Length: 62, dtype: int64

In [6]:
print("\nTaxonomy examples:")
print(gdf[["names", "basic_category", "taxonomy"]].head(20).to_string())

Taxonomy examples:
                                                                                            names                          basic_category                                                                                                                                                                                                         taxonomy
0                                      {'primary': 'Pintu Motors', 'common': None, 'rules': None}                     vehicle_parts_store                                                                     {'primary': 'auto_parts_store', 'hierarchy': ['shopping', 'specialty_store', 'vehicle_parts_store', 'auto_parts_store'], 'alternates': None}
1                        {'primary': 'Thor Guidance Career Point', 'common': None, 'rules': None}                     educational_service                                                                                                        {'primary': 'educational_service', 'hierarchy': ['education', 'educational_service'], 'alternates': None}
2                 {'primary': 'Warud Orange City railway station', 'common': None, 'rules': None}                           train_station                                {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}
3                                        {'primary': 'Sai Mandir', 'common': None, 'rules': None}                  hindu_place_of_worship                                                                  {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}
4     {'primary': 'Late Shri Marutrao Kherade Sabhagruh and Lawn', 'common': None, 'rules': None}                  event_or_party_service                                                        {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}
5                                     {'primary': 'House Of Cafe', 'common': None, 'rules': None}                                    cafe                                                                                                                {'primary': 'cafe', 'hierarchy': ['food_and_drink', 'casual_eatery', 'cafe'], 'alternates': None}
6   {'primary': 'श्री संत शंकर महाराज कृषी महाविद्यालय,पिंपळखूटा', 'common': None, 'rules': None}                       place_of_learning                                                                                                             {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}
7                            {'primary': 'Honey_Bunny cafe warud', 'common': None, 'rules': None}                              restaurant                                                                                                                     {'primary': 'restaurant', 'hierarchy': ['food_and_drink', 'restaurant'], 'alternates': None}
8                               {'primary': 'Rituraj Mobile Shop', 'common': None, 'rules': None}     b2b_office_and_professional_service  {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}
9                         {'primary': 'Genericart Medicine Store', 'common': None, 'rules': None}                 pharmacy_and_drug_store                                                                                 {'primary': 'pharmacy', 'hierarchy': ['shopping', 'specialty_store', 'pharmacy_and_drug_store', 'pharmacy'], 'alternates': None}
10                     {'primary': 'Shrikrishna Ayurvedic Clinic', 'common': None, 'rules': None}  complementary_and_alternative_medicine                            {'primary': 'naturopathic_medicine', 'hierarchy': ['health_care', 'outpatient_care_facility', 'complementary_and_alternative_medicine', 'naturopathic_medicine'], 'alternates': None}
11                      {'primary': 'Warud Ti.warud Di.Amaravati', 'common': None, 'rules': None}                                shopping                                                                                                                                           {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}
12                               {'primary': 'Govansh Dairy Farm', 'common': None, 'rules': None}                                    farm                                                                              {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}
13                                 {'primary': 'Urdu High School', 'common': None, 'rules': None}                               education                                                                                                                                         {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}
14  {'primary': 'Tata Motors Cars Showroom - Jaika Motors, Warud', 'common': None, 'rules': None}                      automotive_service                                                                       {'primary': 'automotive_service', 'hierarchy': ['travel_and_transportation', 'vehicle_service', 'automotive_service'], 'alternates': None}
15                {'primary': 'Saishri Kirana And  General,WARUD', 'common': None, 'rules': None}                 food_and_beverage_store                                                                                          {'primary': 'grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store'], 'alternates': None}
16                {'primary': 'Warud Orange City Railway Station', 'common': None, 'rules': None}                           train_station                                {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}
17                              {'primary': 'Prabhakar Jewellers', 'common': None, 'rules': None}               fashion_and_apparel_store                                                                                        {'primary': 'jewelry_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'jewelry_store'], 'alternates': None}
18                                   {'primary': 'Rural Hospital', 'common': None, 'rules': None}                                hospital                                                                                                                            {'primary': 'hospital', 'hierarchy': ['health_care', 'hospital'], 'alternates': None}
19                                           {'primary': 'TRENDS', 'common': None, 'rules': None}               fashion_and_apparel_store                                                                                      {'primary': 'clothing_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'clothing_store'], 'alternates': None}

In [7]:
print("\nConfidence:")
print(gdf["confidence"].describe())

Confidence:
count    200.000000
mean       0.601143
std        0.215222
min        0.101744
25%        0.444550
50%        0.588211
75%        0.770000
max        1.000000
Name: confidence, dtype: float64

In [7]:
# 1. Check missing values
gdf[[
    "id",
    "names",
    "basic_category",
    "confidence",
    "geometry"
]].isnull().sum()
# 2. Check coordinate system
print("CRS:", gdf.crs)
# 3. Check invalid/empty geometries
print("Empty geometries:", gdf.geometry.is_empty.sum())
print("Missing geometries:", gdf.geometry.isna().sum())
print("Invalid geometries:", (~gdf.geometry.is_valid).sum())

CRS: EPSG:4326
Empty geometries: 0
Missing geometries: 0
Invalid geometries: 0

In [8]:
# Keep only useful columns for Udyam360

gdf_clean = gdf[[
    "id",
    "names",
    "basic_category",
    "taxonomy",
    "confidence",
    "addresses",
    "phones",
    "websites",
    "geometry"
]].copy()

print("Records:", len(gdf_clean))
print("Columns:", gdf_clean.columns.tolist())

Records: 200
Columns: ['id', 'names', 'basic_category', 'taxonomy', 'confidence', 'addresses', 'phones', 'websites', 'geometry']

In [9]:
gdf_clean["names"].head(20)

0     {'primary': 'Pintu Motors', 'common': None, 'r...
1     {'primary': 'Thor Guidance Career Point', 'com...
2     {'primary': 'Warud Orange City railway station...
3     {'primary': 'Sai Mandir', 'common': None, 'rul...
4     {'primary': 'Late Shri Marutrao Kherade Sabhag...
5     {'primary': 'House Of Cafe', 'common': None, '...
6     {'primary': 'श्री संत शंकर महाराज कृषी महाविद्...
7     {'primary': 'Honey_Bunny cafe warud', 'common'...
8     {'primary': 'Rituraj Mobile Shop', 'common': N...
9     {'primary': 'Genericart Medicine Store', 'comm...
10    {'primary': 'Shrikrishna Ayurvedic Clinic', 'c...
11    {'primary': 'Warud Ti.warud Di.Amaravati', 'co...
12    {'primary': 'Govansh Dairy Farm', 'common': No...
13    {'primary': 'Urdu High School', 'common': None...
14    {'primary': 'Tata Motors Cars Showroom - Jaika...
15    {'primary': 'Saishri Kirana And  General,WARUD...
16    {'primary': 'Warud Orange City Railway Station...
17    {'primary': 'Prabhakar Jewellers', 'common': N...
18    {'primary': 'Rural Hospital', 'common': None, ...
19    {'primary': 'TRENDS', 'common': None, 'rules':...
Name: names, dtype: object

In [10]:
# Extract primary business name

gdf_clean["business_name"] = gdf_clean["names"].apply(
    lambda x: x.get("primary") if isinstance(x, dict) else None
)

# Check the result
gdf_clean[["business_name", "basic_category", "confidence"]].head(20)

,business_name,basic_category,confidence
0,Pintu Motors,vehicle_parts_store,0.319494
1,Thor Guidance Career Point,educational_service,0.396972
2,Warud Orange City railway station,train_station,0.805240
3,Sai Mandir,hindu_place_of_worship,0.561847
4,Late Shri Marutrao Kherade Sabhagruh and Lawn,event_or_party_service,0.682641
5,House Of Cafe,cafe,0.811912
6,"श्री संत शंकर महाराज कृषी महाविद्यालय,पिंपळखूटा",place_of_learning,0.735731
7,Honey_Bunny cafe warud,restaurant,0.726765
8,Rituraj Mobile Shop,b2b_office_and_professional_service,0.547186
9,Genericart Medicine Store,pharmacy_and_drug_store,0.770000
10,Shrikrishna Ayurvedic Clinic,complementary_and_alternative_medicine,0.324990
11,Warud Ti.warud Di.Amaravati,shopping,0.371576
12,Govansh Dairy Farm,farm,0.345247
13,Urdu High School,education,0.353113
14,"Tata Motors Cars Showroom - Jaika Motors, Warud",automotive_service,0.850000
15,"Saishri Kirana And General,WARUD",food_and_beverage_store,0.541063
16,Warud Orange City Railway Station,train_station,0.656819
17,Prabhakar Jewellers,fashion_and_apparel_store,0.356342
18,Rural Hospital,hospital,0.711432
19,TRENDS,fashion_and_apparel_store,0.850000

In [11]:
print("Missing business names:",
      gdf_clean["business_name"].isna().sum())

Missing business names: 0

In [12]:
# Extract simple business name
gdf_clean["business_name"] = gdf_clean["names"].apply(
    lambda x: x.get("primary") if isinstance(x, dict) else None
)

# Extract primary category
gdf_clean["category"] = gdf_clean["taxonomy"].apply(
    lambda x: x.get("primary") if isinstance(x, dict) else None
)

# Check result
gdf_clean[["business_name", "category", "confidence"]].head(20)

,business_name,category,confidence
0,Pintu Motors,auto_parts_store,0.319494
1,Thor Guidance Career Point,educational_service,0.396972
2,Warud Orange City railway station,train_station,0.805240
3,Sai Mandir,hindu_place_of_worship,0.561847
4,Late Shri Marutrao Kherade Sabhagruh and Lawn,party_and_event_planning,0.682641
5,House Of Cafe,cafe,0.811912
6,"श्री संत शंकर महाराज कृषी महाविद्यालय,पिंपळखूटा",school,0.735731
7,Honey_Bunny cafe warud,restaurant,0.726765
8,Rituraj Mobile Shop,b2b_advertising_and_marketing_service,0.547186
9,Genericart Medicine Store,pharmacy,0.770000
10,Shrikrishna Ayurvedic Clinic,naturopathic_medicine,0.324990
11,Warud Ti.warud Di.Amaravati,shopping,0.371576
12,Govansh Dairy Farm,dairy_farm,0.345247
13,Urdu High School,education,0.353113
14,"Tata Motors Cars Showroom - Jaika Motors, Warud",automotive_service,0.850000
15,"Saishri Kirana And General,WARUD",grocery_store,0.541063
16,Warud Orange City Railway Station,train_station,0.656819
17,Prabhakar Jewellers,jewelry_store,0.356342
18,Rural Hospital,hospital,0.711432
19,TRENDS,clothing_store,0.850000

In [13]:
print(gdf_clean["category"].value_counts())

category
hospital                    12
shopping                     9
hotel                        6
restaurant                   6
bank                         6
                            ..
lodging                      1
indian_grocery_store         1
outpatient_care_facility     1
sporting_goods_store         1
religious_organization       1
Name: count, Length: 85, dtype: int64

In [14]:
print("Latitude range:")
print(gdf.geometry.y.min(), "to", gdf.geometry.y.max())

print("\nLongitude range:")
print(gdf.geometry.x.min(), "to", gdf.geometry.x.max())

print("\nOperating status:")
print(gdf["operating_status"].value_counts(dropna=False))

print("\nConfidence groups:")
print(gdf["confidence"].describe())

Latitude range:
21.44536 to 21.48300051

Longitude range:
78.25604009 to 78.30921

Operating status:

KeyError: 'operating_status'

In [ ]:
# Check confidence groups

print("Confidence groups:")

print(
    gdf_clean["confidence"].value_counts(
        bins=[0, 0.3, 0.5, 0.7, 0.8, 0.9, 1.0]
    ).sort_index()
)

In [ ]:
# Keep reasonably reliable business locations

gdf_clean = gdf_clean[gdf_clean["confidence"] >= 0.5].copy()

print("Records after confidence filtering:", len(gdf_clean))

In [ ]:
print("Duplicate IDs:", gdf_clean["id"].duplicated().sum())
print("Duplicate business names:", gdf_clean["business_name"].duplicated().sum())

In [15]:
# Check for businesses located extremely close to each other

from sklearn.neighbors import BallTree
import pandas as pd
import numpy as np

# Convert latitude/longitude to radians
coords = np.radians(gdf_clean[["lat", "lon"]].values)

# Earth's radius in km
earth_radius_km = 6371.0

tree = BallTree(coords, metric="haversine")

# Search within 50 meters
radius_km = 0.05
indices = tree.query_radius(coords, r=radius_km / earth_radius_km)

near_duplicates = []

for i, neighbors in enumerate(indices):
    for j in neighbors:
        if i < j:
            name1 = gdf_clean.iloc[i]["business_name"]
            name2 = gdf_clean.iloc[j]["business_name"]
            
            category1 = gdf_clean.iloc[i]["basic_category"]
            category2 = gdf_clean.iloc[j]["basic_category"]
            
            near_duplicates.append([
                i, j,
                name1, name2,
                category1, category2
            ])

near_duplicates_df = pd.DataFrame(
    near_duplicates,
    columns=[
        "index1", "index2",
        "business1", "business2",
        "category1", "category2"
    ]
)

print("Potential near-duplicate pairs:", len(near_duplicates_df))

near_duplicates_df.head(20)

KeyError: "None of [Index(['lat', 'lon'], dtype='object')] are in the [columns]"

In [16]:
# Check the duplicate business names
duplicates = gdf_clean[
    gdf_clean["business_name"].duplicated(keep=False)
].sort_values("business_name")

duplicates[["business_name", "basic_category", "confidence", "geometry"]]

,business_name,basic_category,confidence,geometry
47,Bank of Maharashtra,bank_or_credit_union,0.850000,POINT (78.2699 21.46894)
191,Bank of Maharashtra,bank_or_credit_union,0.958932,POINT (78.26 21.46)
9,Genericart Medicine Store,pharmacy_and_drug_store,0.770000,POINT (78.27113 21.46624)
20,Genericart Medicine Store,pharmacy_and_drug_store,0.770000,POINT (78.2647 21.47121)
143,Genericart Medicine Store,pharmacy_and_drug_store,0.770000,POINT (78.26816 21.47697)
40,HDFC Bank ATM,bank_or_credit_union,0.998561,POINT (78.26776 21.46851)
128,HDFC Bank ATM,atm,0.850000,POINT (78.2706 21.47546)
108,IndianOil,gas_station,0.471639,POINT (78.26946 21.47612)
192,IndianOil,gas_station,0.524101,POINT (78.30012 21.45113)
36,Shriram Finance Limited,bank_or_credit_union,0.850000,POINT (78.26877 21.46981)
82,Shriram Finance Limited,bank_or_credit_union,0.850000,POINT (78.27076 21.47316)

In [17]:
# Check duplicate businesses using name + category + location

gdf_clean["lat"] = gdf_clean.geometry.y
gdf_clean["lon"] = gdf_clean.geometry.x

duplicates = gdf_clean[
    gdf_clean.duplicated(
        subset=["business_name", "basic_category", "lat", "lon"],
        keep=False
    )
].sort_values("business_name")

duplicates[
    ["business_name", "basic_category", "confidence", "lat", "lon"]
]

Empty DataFrame
Columns: [business_name, basic_category, confidence, lat, lon]
Index: []

In [18]:
print(gdf_clean["basic_category"].value_counts())

basic_category
bank_or_credit_union         15
hospital                     12
fashion_and_apparel_store    10
shopping                      9
restaurant                    7
                             ..
printing_service              1
movie_theater                 1
police_station                1
specialty_school              1
religious_organization        1
Name: count, Length: 62, dtype: int64

In [19]:
def map_category(category):

    if category in [
        "pharmacy_and_drug_store",
        "complementary_and_alternative_medicine"
    ]:
        return "healthcare"

    elif category in [
        "restaurant",
        "cafe",
        "food_and_beverage_store",
        "grocery_store",
        "indian_grocery_store"
    ]:
        return "food_and_grocery"

    elif category in [
        "bank_or_credit_union",
        "atm",
        "financial_service"
    ]:
        return "finance"

    elif category in [
        "clothing_store",
        "fashion_and_apparel_store",
        "jewelry_store"
    ]:
        return "retail_fashion"

    elif category in [
        "automotive_service",
        "car_dealer",
        "motorcycle_dealer"
    ]:
        return "automotive"

    elif category in [
        "hospital",
        "clinic",
        "medical_center"
    ]:
        return "healthcare"

    elif category in [
        "school",
        "specialty_school"
    ]:
        return "education"

    else:
        return "other"


gdf_clean["business_group"] = (
    gdf_clean["basic_category"]
    .apply(map_category)
)

print(gdf_clean["business_group"].value_counts())

business_group
other               124
finance              21
healthcare           20
food_and_grocery     18
retail_fashion       10
automotive            6
education             1
Name: count, dtype: int64

In [20]:
# Check which categories are currently classified as "other"

other_businesses = gdf_clean[
    gdf_clean["business_group"] == "other"
]

print("Number of 'other' businesses:", len(other_businesses))

print("\nCategories classified as OTHER:")
print(
    other_businesses["basic_category"]
    .value_counts()
)

Number of 'other' businesses: 124

Categories classified as OTHER:
basic_category
shopping                               9
electronics_store                      6
education                              6
hardware_home_and_garden_store         6
hotel                                  6
event_or_party_service                 5
place_of_learning                      5
auto_dealer                            5
gas_station                            4
casual_eatery                          4
hindu_place_of_worship                 4
college_university                     3
real_estate_service                    3
manufacturer                           3
personal_or_beauty_service             3
agricultural_service                   2
professional_service                   2
b2b_service                            2
lodging                                2
travel_and_transportation              2
educational_service                    2
vehicle_parts_store                    2
farm                                   2
train_station                          2
government_office                      2
b2b_office_and_professional_service    2
diagnostics_imaging_or_lab_service     1
public_transit_facility_or_service     1
travel_service                         1
community_and_government               1
toys_and_games_store                   1
wellness_service                       1
nature_reserve                         1
technical_service                      1
home_service                           1
high_school                            1
social_or_community_service            1
behavioral_or_mental_health_clinic     1
tutoring_service                       1
specialized_health_care                1
police_station                         1
sporting_goods_store                   1
outpatient_care_facility               1
movie_theater                          1
printing_service                       1
sports_and_recreation                  1
books_music_and_video_store            1
sport_league                           1
gym                                    1
religious_organization                 1
Name: count, dtype: int64

In [21]:
# See actual business names + categories that are currently "other"

other_businesses[
    ["business_name", "basic_category", "confidence"]
].sort_values("basic_category")

,business_name,basic_category,confidence
166,C K AGRI CLINIc,agricultural_service,0.629650
183,Swaraj Tractor - M/S Prasanna Tractors,agricultural_service,0.706052
69,"Ketan Hyundai, Warud",auto_dealer,0.878655
165,Tata Motors Cars,auto_dealer,0.719062
116,Bajaj Gurukrupa Bajaj,auto_dealer,0.479004
...,...,...,...
111,GMart Warud,None,0.714257
123,Exide Care - V.K. Trading Co,None,0.965500
163,Taro Pumps - Sanjay Electricals,None,0.603940
174,SMFG India Credit Co. Limited - Warud (Branch),None,0.850000
180,Warud Bus Stand,None,0.479774

In [22]:
other_businesses[
    ["business_name", "basic_category", "taxonomy", "confidence"]
].to_string(index=False)

"                                                            business_name                      basic_category                                                                                                                                                                                                            taxonomy  confidence\n                                                             Pintu Motors                 vehicle_parts_store                                                                        {'primary': 'auto_parts_store', 'hierarchy': ['shopping', 'specialty_store', 'vehicle_parts_store', 'auto_parts_store'], 'alternates': None}    0.319494\n                                               Thor Guidance Career Point                 educational_service                                                                                                           {'primary': 'educational_service', 'hierarchy': ['education', 'educational_service'], 'alternates': None}    0.396972\n                                        Warud Orange City railway station                       train_station                                   {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}    0.805240\n                                                               Sai Mandir              hindu_place_of_worship                                                                     {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}    0.561847\n                            Late Shri Marutrao Kherade Sabhagruh and Lawn              event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.682641\n                          श्री संत शंकर महाराज कृषी महाविद्यालय,पिंपळखूटा                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.735731\n                                                      Rituraj Mobile Shop b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.547186\n                                              Warud Ti.warud Di.Amaravati                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.371576\n                                                       Govansh Dairy Farm                                farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.345247\n                                                         Urdu High School                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.353113\n                                        Warud Orange City Railway Station                       train_station                                   {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}    0.656819\n                                    Shradha Auto Services - Hero MotoCorp                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.965500\n                                              Jain Cold Drinks and Sweets                       casual_eatery                                                                                                   {'primary': 'dessert_shop', 'hierarchy': ['food_and_drink', 'casual_eatery', 'dessert_shop'], 'alternates': None}    0.568382\n                                                           Nature's Pride                 real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.527956\n                                                                 Aakhirah                                None                                                                                                                                                                                                                None    0.101744\n                                              LIC Recruitment & Training  b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.171763\n                                                   Arogyadhara dairy farm                                farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.242642\n               Takarkhede Automotive E-Bike Pandhurna Chwok Warud 444906                          auto_dealer                                                                                                          {'primary': 'auto_dealer', 'hierarchy': ['shopping', 'vehicle_dealer', 'auto_dealer'], 'alternates': None}    0.622938\n                                                  Khatri Gift and Khilona      hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.209797\n                                                        Vidarbha Hardware      hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.929997\n                                               Jain Sales Electronic Shop                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.325508\n                                             Appasaheb Deshmukh Vidyalaya                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.378895\n                                                              Nath Temple              hindu_place_of_worship                                                                     {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}    0.348269\n                                                       Manappuram Finance              event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.900138\n                                                           Police Station                      police_station                                                                             {'primary': 'police_station', 'hierarchy': ['community_and_government', 'public_safety_service', 'police_station'], 'alternates': None}    0.365536\n                                        Raj Associates Property Solutions                 real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.366064\n                                                            Vijay Theatre                       movie_theater                                                                                                          {'primary': 'movie_theater', 'hierarchy': ['arts_and_entertainment', 'movie_theater'], 'alternates': None}    0.655338\n                                                         Chambole Alankar                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.411425\n                                                             Sayali Metal                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.517452\n                                                                 Art Zone                    printing_service                                                                                                     {'primary': 'printing_service', 'hierarchy': ['services_and_business', 'printing_service'], 'alternates': None}    0.185143\n                                    Pavan Khasbage Fitness and Supplement               sports_and_recreation                                                                                                                    {'primary': 'sports_and_recreation', 'hierarchy': ['sports_and_recreation'], 'alternates': None}    0.582980\n                                  Doctor S Deshmukh Jagrut Primary School                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.395698\n                                                   New Kale Traders,Warud          personal_or_beauty_service                                                                                      {'primary': 'hair_salon', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'hair_salon'], 'alternates': None}    0.309188\n         Warud Taluka Sarkari and Nimsarkari Karmchari Sahkari Patsanstha                   government_office                                                                                                {'primary': 'government_office', 'hierarchy': ['community_and_government', 'government_office'], 'alternates': None}    0.253037\n                                                School of Scholars, Warud                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.897575\n                                       Californiya Cricket Academy, Warud                        sport_league                                                                                                                                                                                                                None    0.696841\n                                                                Sai tiles      hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.453960\n                                                        Hotel Nature Food                               hotel                                                                                                                                         {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}    0.649806\n                                                     Ketan Hyundai, Warud                         auto_dealer                                                                                                          {'primary': 'auto_dealer', 'hierarchy': ['shopping', 'vehicle_dealer', 'auto_dealer'], 'alternates': None}    0.878655\n                                                    Sahajivan Social Club         social_or_community_service                                                                            {'primary': 'social_or_community_service', 'hierarchy': ['community_and_government', 'social_or_community_service'], 'alternates': None}    0.200603\n                                             Malode Bichayat and Caterers              event_or_party_service                                                                                             {'primary': 'caterer', 'hierarchy': ['services_and_business', 'event_or_party_service', 'caterer'], 'alternates': None}    0.596224\n                                              Black Diamond Tattoo Studio          personal_or_beauty_service                                               {'primary': 'tattoo_and_piercing', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'body_modification', 'tattoo_and_piercing'], 'alternates': None}    0.223191\n                                                                Cake Zone                       casual_eatery                                                                                                   {'primary': 'dessert_shop', 'hierarchy': ['food_and_drink', 'casual_eatery', 'dessert_shop'], 'alternates': None}    0.605738\n                                Shri Vishwayan Ayurveda Panchkarma Clinic  behavioral_or_mental_health_clinic                             {'primary': 'family_counseling', 'hierarchy': ['health_care', 'outpatient_care_facility', 'behavioral_or_mental_health_clinic', 'counseling', 'family_counseling'], 'alternates': None}    0.573966\n                                                                Kings Gym                                 gym                                                                                                  {'primary': 'gym', 'hierarchy': ['sports_and_recreation', 'sport_or_fitness_facility', 'gym'], 'alternates': None}    0.811074\n                                              Veera Mobile and Electronic                   electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.253770\n                                                      Hindustan Petroleum                         gas_station                                                                                        {'primary': 'gas_station', 'hierarchy': ['travel_and_transportation', 'fueling_station', 'gas_station'], 'alternates': None}    0.954000\n                                                     Saraswati Book Depot         books_music_and_video_store                                                                              {'primary': 'bookstore', 'hierarchy': ['shopping', 'specialty_store', 'books_music_and_video_store', 'bookstore'], 'alternates': None}    0.483612\n                                 Shri Gajanan Hardware and Plywood Centre      hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.324062\n                                                                    Warud                             lodging                                                                                                                                                {'primary': 'lodging', 'hierarchy': ['lodging'], 'alternates': None}    0.593391\n                                                             Deote Bakery                       casual_eatery                                                                                                               {'primary': 'bakery', 'hierarchy': ['food_and_drink', 'casual_eatery', 'bakery'], 'alternates': None}    0.393940\n                                  Shri Gurudev krushi kendra Rajura bazar                         b2b_service                                                                     {'primary': 'agriculture', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_agriculture_service', 'agriculture'], 'alternates': None}    0.558234\n                                                         Hanifa Furniture                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.289267\n                                                            Patel traders                        manufacturer                                                                                              {'primary': 'manufacturer', 'hierarchy': ['services_and_business', 'b2b_service', 'manufacturer'], 'alternates': None}    0.410479\n                             Belsare Multi Speciality Homoeopathic Clinic            outpatient_care_facility                                                                                               {'primary': 'outpatient_care_facility', 'hierarchy': ['health_care', 'outpatient_care_facility'], 'alternates': None}    0.382472\n                                                          SS Mobile Warud                   electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.327947\n                                                     Shivam Sports, warud                sporting_goods_store                                                                                       {'primary': 'sporting_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'sporting_goods_store'], 'alternates': None}    0.570937\n                                                      Sarvodaya Computers                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.144030\n                                                    New Ambika Collection                            shopping                                                                                                                             

In [23]:
print("Final columns:")
print(gdf_clean.columns.tolist())

print("\nNumber of records:")
print(len(gdf_clean))

print("\nMissing values:")
print(gdf_clean.isna().sum())

Final columns:
['id', 'names', 'basic_category', 'taxonomy', 'confidence', 'addresses', 'phones', 'websites', 'geometry', 'business_name', 'category', 'lat', 'lon', 'business_group']

Number of records:
200

Missing values:
id                  0
names               0
basic_category      6
taxonomy            7
confidence          0
addresses           0
phones             57
websites          124
geometry            0
business_name       0
category            7
lat                 0
lon                 0
business_group      0
dtype: int64

In [24]:
print("CRS:", gdf_clean.crs)

CRS: EPSG:4326

In [25]:
if "operating_status" in gdf_clean.columns:
    print(gdf_clean["operating_status"].value_counts(dropna=False))
else:
    print("operating_status column not available")

operating_status column not available

In [26]:
print("Missing latitude:", gdf_clean["lat"].isna().sum())
print("Missing longitude:", gdf_clean["lon"].isna().sum())

print(gdf_clean[["business_name", "lat", "lon"]].head())

Missing latitude: 0
Missing longitude: 0
                                   business_name        lat        lon
0                                   Pintu Motors  21.475815  78.277436
1                     Thor Guidance Career Point  21.471763  78.276240
2              Warud Orange City railway station  21.458721  78.276164
3                                     Sai Mandir  21.466389  78.281386
4  Late Shri Marutrao Kherade Sabhagruh and Lawn  21.466042  78.275646

In [27]:
from sklearn.neighbors import BallTree
import numpy as np
import pandas as pd

# Work on a copy
check_df = gdf_clean.copy()

# Convert lat/lon to radians
coords = np.radians(check_df[["lat", "lon"]].values)

# Earth radius in km
EARTH_RADIUS_KM = 6371.0088

# Create spatial tree
tree = BallTree(coords, metric="haversine")

# Search within 50 metres
radius_km = 0.05
radius_rad = radius_km / EARTH_RADIUS_KM

neighbors = tree.query_radius(coords, r=radius_rad)

# Find possible duplicate pairs
possible_duplicates = []

for i, nearby in enumerate(neighbors):
    for j in nearby:
        if i < j:
            name1 = str(check_df.iloc[i]["business_name"]).strip().lower()
            name2 = str(check_df.iloc[j]["business_name"]).strip().lower()

            cat1 = str(check_df.iloc[i]["basic_category"]).strip().lower()
            cat2 = str(check_df.iloc[j]["basic_category"]).strip().lower()

            if name1 == name2 and cat1 == cat2:
                possible_duplicates.append((i, j))

print("Possible nearby duplicates:", len(possible_duplicates))

Possible nearby duplicates: 0

In [28]:
other_businesses = gdf_clean[
    gdf_clean["business_group"] == "other"
][
    ["business_name", "basic_category", "taxonomy", "confidence"]
]

print(other_businesses.to_string(index=False))

                                                            business_name                      basic_category                                                                                                                                                                                                            taxonomy  confidence
                                                             Pintu Motors                 vehicle_parts_store                                                                        {'primary': 'auto_parts_store', 'hierarchy': ['shopping', 'specialty_store', 'vehicle_parts_store', 'auto_parts_store'], 'alternates': None}    0.319494
                                               Thor Guidance Career Point                 educational_service                                                                                                           {'primary': 'educational_service', 'hierarchy': ['education', 'educational_service'], 'alternates': None}    0.396972
                                        Warud Orange City railway station                       train_station                                   {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}    0.805240
                                                               Sai Mandir              hindu_place_of_worship                                                                     {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}    0.561847
                            Late Shri Marutrao Kherade Sabhagruh and Lawn              event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.682641
                          श्री संत शंकर महाराज कृषी महाविद्यालय,पिंपळखूटा                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.735731
                                                      Rituraj Mobile Shop b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.547186
                                              Warud Ti.warud Di.Amaravati                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.371576
                                                       Govansh Dairy Farm                                farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.345247
                                                         Urdu High School                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.353113
                                        Warud Orange City Railway Station                       train_station                                   {'primary': 'train_station', 'hierarchy': ['travel_and_transportation', 'ground_transport_facility_or_service', 'rail_facility_or_service', 'train_station'], 'alternates': None}    0.656819
                                    Shradha Auto Services - Hero MotoCorp                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.965500
                                              Jain Cold Drinks and Sweets                       casual_eatery                                                                                                   {'primary': 'dessert_shop', 'hierarchy': ['food_and_drink', 'casual_eatery', 'dessert_shop'], 'alternates': None}    0.568382
                                                           Nature's Pride                 real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.527956
                                                                 Aakhirah                                None                                                                                                                                                                                                                None    0.101744
                                              LIC Recruitment & Training  b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.171763
                                                   Arogyadhara dairy farm                                farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.242642
               Takarkhede Automotive E-Bike Pandhurna Chwok Warud 444906                          auto_dealer                                                                                                          {'primary': 'auto_dealer', 'hierarchy': ['shopping', 'vehicle_dealer', 'auto_dealer'], 'alternates': None}    0.622938
                                                  Khatri Gift and Khilona      hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.209797
                                                        Vidarbha Hardware      hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.929997
                                               Jain Sales Electronic Shop                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.325508
                                             Appasaheb Deshmukh Vidyalaya                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.378895
                                                              Nath Temple              hindu_place_of_worship                                                                     {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}    0.348269
                                                       Manappuram Finance              event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.900138
                                                           Police Station                      police_station                                                                             {'primary': 'police_station', 'hierarchy': ['community_and_government', 'public_safety_service', 'police_station'], 'alternates': None}    0.365536
                                        Raj Associates Property Solutions                 real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.366064
                                                            Vijay Theatre                       movie_theater                                                                                                          {'primary': 'movie_theater', 'hierarchy': ['arts_and_entertainment', 'movie_theater'], 'alternates': None}    0.655338
                                                         Chambole Alankar                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.411425
                                                             Sayali Metal                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.517452
                                                                 Art Zone                    printing_service                                                                                                     {'primary': 'printing_service', 'hierarchy': ['services_and_business', 'printing_service'], 'alternates': None}    0.185143
                                    Pavan Khasbage Fitness and Supplement               sports_and_recreation                                                                                                                    {'primary': 'sports_and_recreation', 'hierarchy': ['sports_and_recreation'], 'alternates': None}    0.582980
                                  Doctor S Deshmukh Jagrut Primary School                           education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.395698
                                                   New Kale Traders,Warud          personal_or_beauty_service                                                                                      {'primary': 'hair_salon', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'hair_salon'], 'alternates': None}    0.309188
         Warud Taluka Sarkari and Nimsarkari Karmchari Sahkari Patsanstha                   government_office                                                                                                {'primary': 'government_office', 'hierarchy': ['community_and_government', 'government_office'], 'alternates': None}    0.253037
                                                School of Scholars, Warud                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.897575
                                       Californiya Cricket Academy, Warud                        sport_league                                                                                                                                                                                                                None    0.696841
                                                                Sai tiles      hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.453960
                                                        Hotel Nature Food                               hotel                                                                                                                                         {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}    0.649806
                                                     Ketan Hyundai, Warud                         auto_dealer                                                                                                          {'primary': 'auto_dealer', 'hierarchy': ['shopping', 'vehicle_dealer', 'auto_dealer'], 'alternates': None}    0.878655
                                                    Sahajivan Social Club         social_or_community_service                                                                            {'primary': 'social_or_community_service', 'hierarchy': ['community_and_government', 'social_or_community_service'], 'alternates': None}    0.200603
                                             Malode Bichayat and Caterers              event_or_party_service                                                                                             {'primary': 'caterer', 'hierarchy': ['services_and_business', 'event_or_party_service', 'caterer'], 'alternates': None}    0.596224
                                              Black Diamond Tattoo Studio          personal_or_beauty_service                                               {'primary': 'tattoo_and_piercing', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'body_modification', 'tattoo_and_piercing'], 'alternates': None}    0.223191
                                                                Cake Zone                       casual_eatery                                                                                                   {'primary': 'dessert_shop', 'hierarchy': ['food_and_drink', 'casual_eatery', 'dessert_shop'], 'alternates': None}    0.605738
                                Shri Vishwayan Ayurveda Panchkarma Clinic  behavioral_or_mental_health_clinic                             {'primary': 'family_counseling', 'hierarchy': ['health_care', 'outpatient_care_facility', 'behavioral_or_mental_health_clinic', 'counseling', 'family_counseling'], 'alternates': None}    0.573966
                                                                Kings Gym                                 gym                                                                                                  {'primary': 'gym', 'hierarchy': ['sports_and_recreation', 'sport_or_fitness_facility', 'gym'], 'alternates': None}    0.811074
                                              Veera Mobile and Electronic                   electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.253770
                                                      Hindustan Petroleum                         gas_station                                                                                        {'primary': 'gas_station', 'hierarchy': ['travel_and_transportation', 'fueling_station', 'gas_station'], 'alternates': None}    0.954000
                                                     Saraswati Book Depot         books_music_and_video_store                                                                              {'primary': 'bookstore', 'hierarchy': ['shopping', 'specialty_store', 'books_music_and_video_store', 'bookstore'], 'alternates': None}    0.483612
                                 Shri Gajanan Hardware and Plywood Centre      hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.324062
                                                                    Warud                             lodging                                                                                                                                                {'primary': 'lodging', 'hierarchy': ['lodging'], 'alternates': None}    0.593391
                                                             Deote Bakery                       casual_eatery                                                                                                               {'primary': 'bakery', 'hierarchy': ['food_and_drink', 'casual_eatery', 'bakery'], 'alternates': None}    0.393940
                                  Shri Gurudev krushi kendra Rajura bazar                         b2b_service                                                                     {'primary': 'agriculture', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_agriculture_service', 'agriculture'], 'alternates': None}    0.558234
                                                         Hanifa Furniture                            shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.289267
                                                            Patel traders                        manufacturer                                                                                              {'primary': 'manufacturer', 'hierarchy': ['services_and_business', 'b2b_service', 'manufacturer'], 'alternates': None}    0.410479
                             Belsare Multi Speciality Homoeopathic Clinic            outpatient_care_facility                                                                                               {'primary': 'outpatient_care_facility', 'hierarchy': ['health_care', 'outpatient_care_facility'], 'alternates': None}    0.382472
                                                          SS Mobile Warud                   electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.327947
                                                     Shivam Sports, warud                sporting_goods_store                                                                                       {'primary': 'sporting_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'sporting_goods_store'], 'alternates': None}    0.570937
                                                      Sarvodaya Computers                   place_of_learning                                                                                                                {'primary': 'school', 'hierarchy': ['education', 'place_of_learning', 'school'], 'alternates': None}    0.144030

In [29]:
def get_category(row):
    basic = str(row["basic_category"]).lower()
    
    taxonomy = row["taxonomy"]
    taxonomy_text = str(taxonomy).lower()

    # Finance
    if any(x in basic or x in taxonomy_text for x in [
        "bank", "finance", "loan", "credit", "atm", "insurance"
    ]):
        return "finance"

    # Healthcare
    if any(x in basic or x in taxonomy_text for x in [
        "pharmacy", "hospital", "clinic", "medical",
        "health", "doctor", "dentist", "wellness"
    ]):
        return "healthcare"

    # Food & Grocery
    if any(x in basic or x in taxonomy_text for x in [
        "restaurant", "food", "grocery", "supermarket",
        "bakery", "cafe", "fruit", "vegetable"
    ]):
        return "food_and_grocery"

    # Agriculture
    if any(x in basic or x in taxonomy_text for x in [
        "agricultural", "farm", "tractor", "fertilizer",
        "seed", "agro", "agriculture"
    ]):
        return "agriculture"

    # Education
    if any(x in basic or x in taxonomy_text for x in [
        "school", "college", "education", "learning",
        "training", "coaching"
    ]):
        return "education"

    # Automotive
    if any(x in basic or x in taxonomy_text for x in [
        "auto", "automotive", "vehicle", "car", "motorcycle",
        "repair", "tyre"
    ]):
        return "automotive"

    # Retail
    if any(x in basic or x in taxonomy_text for x in [
        "shopping", "retail", "clothing", "fashion",
        "store", "shop", "market"
    ]):
        return "retail"

    # Professional services
    if any(x in basic or x in taxonomy_text for x in [
        "professional", "office", "accounting",
        "legal", "consulting", "advertising"
    ]):
        return "professional_services"

    # Transport
    if any(x in basic or x in taxonomy_text for x in [
        "transport", "train_station", "bus",
        "railway", "taxi"
    ]):
        return "transport"

    return "other"

In [30]:
gdf_clean["business_group"] = gdf_clean.apply(get_category, axis=1)

print(gdf_clean["business_group"].value_counts())

business_group
retail                   35
other                    30
transport                26
healthcare               25
food_and_grocery         22
education                19
finance                  18
automotive               15
agriculture               6
professional_services     4
Name: count, dtype: int64

In [31]:
print(
    gdf_clean[
        gdf_clean["business_group"] == "other"
    ][["business_name", "basic_category", "taxonomy"]]
    .to_string(index=False)
)

                                 business_name              basic_category                                                                                                                                                              taxonomy
                                    Sai Mandir      hindu_place_of_worship                       {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}
                                      Aakhirah                        None                                                                                                                                                                  None
                                   Nath Temple      hindu_place_of_worship                       {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}
                                Police Station              police_station                               {'primary': 'police_station', 'hierarchy': ['community_and_government', 'public_safety_service', 'police_station'], 'alternates': None}
                                 Vijay Theatre               movie_theater                                                            {'primary': 'movie_theater', 'hierarchy': ['arts_and_entertainment', 'movie_theater'], 'alternates': None}
         Pavan Khasbage Fitness and Supplement       sports_and_recreation                                                                      {'primary': 'sports_and_recreation', 'hierarchy': ['sports_and_recreation'], 'alternates': None}
                        New Kale Traders,Warud  personal_or_beauty_service                                        {'primary': 'hair_salon', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'hair_salon'], 'alternates': None}
            Californiya Cricket Academy, Warud                sport_league                                                                                                                                                                  None
                             Hotel Nature Food                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                         Sahajivan Social Club social_or_community_service                              {'primary': 'social_or_community_service', 'hierarchy': ['community_and_government', 'social_or_community_service'], 'alternates': None}
                   Black Diamond Tattoo Studio  personal_or_beauty_service {'primary': 'tattoo_and_piercing', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'body_modification', 'tattoo_and_piercing'], 'alternates': None}
                                     Kings Gym                         gym                                                    {'primary': 'gym', 'hierarchy': ['sports_and_recreation', 'sport_or_fitness_facility', 'gym'], 'alternates': None}
                                         Warud                     lodging                                                                                                  {'primary': 'lodging', 'hierarchy': ['lodging'], 'alternates': None}
                            Glam Studios Warud  personal_or_beauty_service                                    {'primary': 'beauty_salon', 'hierarchy': ['lifestyle_services', 'personal_or_beauty_service', 'beauty_salon'], 'alternates': None}
                                   GMart Warud                        None                                                                                                                                                                  None
                  Exide Care - V.K. Trading Co                        None                                                                                                                                                                  None
                                Trimurti Lodge                     lodging                                                                                           {'primary': 'lodge', 'hierarchy': ['lodging', 'lodge'], 'alternates': None}
                      Hotel Sagar and Wine Bar                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                        HOTEL Vrundavan ,warud                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                                  Hotel Rimzim                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                                         Zunja              nature_reserve                                             {'primary': 'nature_reserve', 'hierarchy': ['geographic_entities', 'land_feature', 'nature_reserve'], 'alternates': None}
               Taro Pumps - Sanjay Electricals                        None                                                                                                                                                                  None
                         grampanchayat dhanodi    community_and_government                                                                {'primary': 'community_and_government', 'hierarchy': ['community_and_government'], 'alternates': None}
SMFG India Credit Co. Limited - Warud (Branch)                        None                                                                                                                                                                  None
                                    Gavhankund      hindu_place_of_worship                       {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}
             KhteshwerBikaner Sweet Mart Warud                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                               Warud Bus Stand                        None                                                                                                                                                                  None
             Shri Kheteswar Bikaner Sweet Mart                       hotel                                                                                           {'primary': 'hotel', 'hierarchy': ['lodging', 'hotel'], 'alternates': None}
                        Gajanan Maharaj Temple      hindu_place_of_worship                       {'primary': 'hindu_place_of_worship', 'hierarchy': ['cultural_and_historic', 'place_of_worship', 'hindu_place_of_worship'], 'alternates': None}
                              Masjid E Gausiya      religious_organization                                           {'primary': 'religious_organization', 'hierarchy': ['cultural_and_historic', 'religious_organization'], 'alternates': None}

In [32]:
other_businesses = gdf_clean[
    gdf_clean["business_group"] == "other"
][[
    "business_name",
    "basic_category",
    "taxonomy",
    "confidence",
    "lat",
    "lon"
]]

print("Number of OTHER businesses:", len(other_businesses))

display(other_businesses)

Number of OTHER businesses: 30

,business_name,basic_category,taxonomy,confidence,lat,lon
3,Sai Mandir,hindu_place_of_worship,"{'primary': 'hindu_place_of_worship', 'hierarc...",0.561847,21.466389,78.281386
26,Aakhirah,None,None,0.101744,21.471690,78.267400
38,Nath Temple,hindu_place_of_worship,"{'primary': 'hindu_place_of_worship', 'hierarc...",0.348269,21.469071,78.266486
44,Police Station,police_station,"{'primary': 'police_station', 'hierarchy': ['c...",0.365536,21.467266,78.269797
46,Vijay Theatre,movie_theater,"{'primary': 'movie_theater', 'hierarchy': ['ar...",0.655338,21.468518,78.269889
55,Pavan Khasbage Fitness and Supplement,sports_and_recreation,"{'primary': 'sports_and_recreation', 'hierarch...",0.582980,21.468187,78.271427
61,"New Kale Traders,Warud",personal_or_beauty_service,"{'primary': 'hair_salon', 'hierarchy': ['lifes...",0.309188,21.469203,78.273056
65,"Californiya Cricket Academy, Warud",sport_league,None,0.696841,21.469600,78.272900
68,Hotel Nature Food,hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.649806,21.473046,78.273233
71,Sahajivan Social Club,social_or_community_service,"{'primary': 'social_or_community_service', 'hi...",0.200603,21.473991,78.275921
74,Black Diamond Tattoo Studio,personal_or_beauty_service,"{'primary': 'tattoo_and_piercing', 'hierarchy'...",0.223191,21.475053,78.273106
79,Kings Gym,gym,"{'primary': 'gym', 'hierarchy': ['sports_and_r...",0.811074,21.474332,78.270622
88,Warud,lodging,"{'primary': 'lodging', 'hierarchy': ['lodging'...",0.593391,21.472290,78.269150
106,Glam Studios Warud,personal_or_beauty_service,"{'primary': 'beauty_salon', 'hierarchy': ['lif...",0.827332,21.474497,78.268903
111,GMart Warud,None,None,0.714257,21.476046,78.270002
123,Exide Care - V.K. Trading Co,None,None,0.965500,21.476280,78.271684
125,Trimurti Lodge,lodging,"{'primary': 'lodge', 'hierarchy': ['lodging', ...",0.731925,21.476620,78.271307
131,Hotel Sagar and Wine Bar,hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.719171,21.476795,78.273073
150,"HOTEL Vrundavan ,warud",hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.564739,21.476700,78.267837
151,Hotel Rimzim,hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.701082,21.476700,78.267840
160,Zunja,nature_reserve,"{'primary': 'nature_reserve', 'hierarchy': ['g...",0.580611,21.476780,78.267830
163,Taro Pumps - Sanjay Electricals,None,None,0.603940,21.476780,78.267830
168,grampanchayat dhanodi,community_and_government,"{'primary': 'community_and_government', 'hiera...",0.587835,21.476966,78.267818
174,SMFG India Credit Co. Limited - Warud (Branch),None,None,0.850000,21.477891,78.258091
175,Gavhankund,hindu_place_of_worship,"{'primary': 'hindu_place_of_worship', 'hierarc...",0.849741,21.468167,78.256599
178,KhteshwerBikaner Sweet Mart Warud,hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.795624,21.474729,78.260906
180,Warud Bus Stand,None,None,0.479774,21.474442,78.261401
181,Shri Kheteswar Bikaner Sweet Mart,hotel,"{'primary': 'hotel', 'hierarchy': ['lodging', ...",0.556853,21.474000,78.260790
187,Gajanan Maharaj Temple,hindu_place_of_worship,"{'primary': 'hindu_place_of_worship', 'hierarc...",0.657107,21.467558,78.260035
188,Masjid E Gausiya,religious_organization,"{'primary': 'religious_organization', 'hierarc...",0.449962,21.464918,78.259314

In [33]:
def get_primary_taxonomy(x):
    if isinstance(x, dict):
        return x.get("primary")
    return None

other_businesses["taxonomy_primary"] = (
    other_businesses["taxonomy"]
    .apply(get_primary_taxonomy)
)

display(
    other_businesses[
        ["business_name", "basic_category", "taxonomy_primary", "confidence"]
    ].to_string(index=False)
)

'                                 business_name              basic_category            taxonomy_primary  confidence\n                                    Sai Mandir      hindu_place_of_worship      hindu_place_of_worship    0.561847\n                                      Aakhirah                        None                        None    0.101744\n                                   Nath Temple      hindu_place_of_worship      hindu_place_of_worship    0.348269\n                                Police Station              police_station              police_station    0.365536\n                                 Vijay Theatre               movie_theater               movie_theater    0.655338\n         Pavan Khasbage Fitness and Supplement       sports_and_recreation       sports_and_recreation    0.582980\n                        New Kale Traders,Warud  personal_or_beauty_service                  hair_salon    0.309188\n            Californiya Cricket Academy, Warud                sport_league                        None    0.696841\n                             Hotel Nature Food                       hotel                       hotel    0.649806\n                         Sahajivan Social Club social_or_community_service social_or_community_service    0.200603\n                   Black Diamond Tattoo Studio  personal_or_beauty_service         tattoo_and_piercing    0.223191\n                                     Kings Gym                         gym                         gym    0.811074\n                                         Warud                     lodging                     lodging    0.593391\n                            Glam Studios Warud  personal_or_beauty_service                beauty_salon    0.827332\n                                   GMart Warud                        None                        None    0.714257\n                  Exide Care - V.K. Trading Co                        None                        None    0.965500\n                                Trimurti Lodge                     lodging                       lodge    0.731925\n                      Hotel Sagar and Wine Bar                       hotel                       hotel    0.719171\n                        HOTEL Vrundavan ,warud                       hotel                       hotel    0.564739\n                                  Hotel Rimzim                       hotel                       hotel    0.701082\n                                         Zunja              nature_reserve              nature_reserve    0.580611\n               Taro Pumps - Sanjay Electricals                        None                        None    0.603940\n                         grampanchayat dhanodi    community_and_government    community_and_government    0.587835\nSMFG India Credit Co. Limited - Warud (Branch)                        None                        None    0.850000\n                                    Gavhankund      hindu_place_of_worship      hindu_place_of_worship    0.849741\n             KhteshwerBikaner Sweet Mart Warud                       hotel                       hotel    0.795624\n                               Warud Bus Stand                        None                        None    0.479774\n             Shri Kheteswar Bikaner Sweet Mart                       hotel                       hotel    0.556853\n                        Gajanan Maharaj Temple      hindu_place_of_worship      hindu_place_of_worship    0.657107\n                              Masjid E Gausiya      religious_organization      religious_organization    0.449962'

In [34]:
def map_category(category):

    if pd.isna(category):
        return "other"

    category = str(category).lower().strip()

    if category in [
        "bank_or_credit_union",
        "atm",
        "financial_service",
        "loan_agency"
    ]:
        return "finance"

    elif category in [
        "pharmacy_and_drug_store",
        "hospital",
        "medical_center",
        "doctor",
        "clinic"
    ]:
        return "healthcare"

    elif category in [
        "restaurant",
        "casual_eatery",
        "fast_food_restaurant",
        "cafe",
        "bakery"
    ]:
        return "food_and_grocery"

    elif category in [
        "grocery_store",
        "supermarket",
        "convenience_store"
    ]:
        return "food_and_grocery"

    elif category in [
        "auto_dealer",
        "auto_repair",
        "car_dealer",
        "motorcycle_dealer"
    ]:
        return "automotive"

    elif category in [
        "agricultural_service",
        "farm_equipment_store",
        "farm_supply_store"
    ]:
        return "agriculture"

    elif category in [
        "beauty_salon",
        "hair_salon",
        "personal_or_beauty_service"
    ]:
        return "retail_fashion"

    elif category in [
        "hotel",
        "lodging",
        "lodge"
    ]:
        return "hospitality"

    elif category in [
        "gym",
        "sports_and_recreation",
        "sport_league"
    ]:
        return "sports"

    elif category in [
        "school",
        "specialty_school",
        "place_of_learning"
    ]:
        return "education"

    elif category in [
        "hindu_place_of_worship",
        "religious_organization",
        "mosque",
        "church"
    ]:
        return "religious"

    elif category in [
        "police_station",
        "community_and_government",
        "government_office"
    ]:
        return "government"

    elif category in [
        "train_station",
        "bus_station"
    ]:
        return "transport"

    elif category in [
        "movie_theater"
    ]:
        return "entertainment"

    else:
        return "other"

In [35]:
gdf_clean["business_group"] = (
    gdf_clean["basic_category"]
    .apply(map_category)
)

print(gdf_clean["business_group"].value_counts())

business_group
other               107
finance              21
healthcare           17
food_and_grocery     16
hospitality           8
education             6
religious             5
automotive            5
government            4
sports                3
retail_fashion        3
transport             2
agriculture           2
entertainment         1
Name: count, dtype: int64

In [36]:
other_businesses = gdf_clean[
    gdf_clean["business_group"] == "other"
][
    ["business_name",
     "basic_category",
     "taxonomy_primary",
     "confidence",
     "lat",
     "lon"]
]

print(other_businesses.to_string(index=False))

KeyError: "['taxonomy_primary'] not in index"

In [37]:
other_businesses = gdf_clean[
    gdf_clean["business_group"] == "other"
][
    ["business_name",
     "basic_category",
     "taxonomy",
     "confidence",
     "lat",
     "lon"]
]

print(other_businesses.to_string(index=False))

                                                            business_name                         basic_category                                                                                                                                                                                                            taxonomy  confidence       lat       lon
                                                             Pintu Motors                    vehicle_parts_store                                                                        {'primary': 'auto_parts_store', 'hierarchy': ['shopping', 'specialty_store', 'vehicle_parts_store', 'auto_parts_store'], 'alternates': None}    0.319494 21.475815 78.277436
                                               Thor Guidance Career Point                    educational_service                                                                                                           {'primary': 'educational_service', 'hierarchy': ['education', 'educational_service'], 'alternates': None}    0.396972 21.471763 78.276240
                            Late Shri Marutrao Kherade Sabhagruh and Lawn                 event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.682641 21.466042 78.275646
                                                      Rituraj Mobile Shop    b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.547186 21.466200 78.271400
                                             Shrikrishna Ayurvedic Clinic complementary_and_alternative_medicine                               {'primary': 'naturopathic_medicine', 'hierarchy': ['health_care', 'outpatient_care_facility', 'complementary_and_alternative_medicine', 'naturopathic_medicine'], 'alternates': None}    0.324990 21.466444 78.270332
                                              Warud Ti.warud Di.Amaravati                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.371576 21.466401 78.269202
                                                       Govansh Dairy Farm                                   farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.345247 21.466191 78.269669
                                                         Urdu High School                              education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.353113 21.465801 78.269234
                          Tata Motors Cars Showroom - Jaika Motors, Warud                     automotive_service                                                                          {'primary': 'automotive_service', 'hierarchy': ['travel_and_transportation', 'vehicle_service', 'automotive_service'], 'alternates': None}    0.850000 21.464375 78.272377
                                        Saishri Kirana And  General,WARUD                food_and_beverage_store                                                                                             {'primary': 'grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store'], 'alternates': None}    0.541063 21.458800 78.275790
                                                      Prabhakar Jewellers              fashion_and_apparel_store                                                                                           {'primary': 'jewelry_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'jewelry_store'], 'alternates': None}    0.356342 21.466705 78.268394
                                                                   TRENDS              fashion_and_apparel_store                                                                                         {'primary': 'clothing_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'clothing_store'], 'alternates': None}    0.850000 21.471210 78.264700
                                    Shradha Auto Services - Hero MotoCorp                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.965500 21.471210 78.264700
                                                           Nature's Pride                    real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.527956 21.471690 78.267400
                                                                 Aakhirah                                   None                                                                                                                                                                                                                None    0.101744 21.471690 78.267400
                                              LIC Recruitment & Training     b2b_office_and_professional_service     {'primary': 'b2b_advertising_and_marketing_service', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_office_and_professional_service', 'b2b_advertising_and_marketing_service'], 'alternates': None}    0.171763 21.471690 78.267400
                                                   Arogyadhara dairy farm                                   farm                                                                                 {'primary': 'dairy_farm', 'hierarchy': ['services_and_business', 'agricultural_service', 'farm', 'dairy_farm'], 'alternates': None}    0.242642 21.471690 78.267400
                                                     Sakshi Sarees Center              fashion_and_apparel_store                                                         {'primary': 'womens_clothing_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'clothing_store', 'womens_clothing_store'], 'alternates': None}    0.440413 21.471590 78.268754
                                                  Khatri Gift and Khilona         hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.209797 21.471444 78.268546
                                                        Vidarbha Hardware         hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.929997 21.471390 78.268790
                                               Jain Sales Electronic Shop                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.325508 21.470851 78.268750
                                             Appasaheb Deshmukh Vidyalaya                              education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.378895 21.470290 78.265267
                                                       Motha Bhaji Bazaar                food_and_beverage_store                                                                                             {'primary': 'grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store'], 'alternates': None}    0.338880 21.468190 78.267865
                                                  HDFC Securities - Warud                food_and_beverage_store                                                            {'primary': 'ethical_grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store', 'ethical_grocery_store'], 'alternates': None}    0.965500 21.468505 78.267760
                                                       Manappuram Finance                 event_or_party_service                                                           {'primary': 'party_and_event_planning', 'hierarchy': ['services_and_business', 'event_or_party_service', 'party_and_event_planning'], 'alternates': None}    0.900138 21.468477 78.267762
                                                       Shrikant Jewellers              fashion_and_apparel_store                                                                                           {'primary': 'jewelry_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'jewelry_store'], 'alternates': None}    0.961536 21.467247 78.268559
                                        Raj Associates Property Solutions                    real_estate_service                                                                                               {'primary': 'real_estate_service', 'hierarchy': ['services_and_business', 'real_estate_service'], 'alternates': None}    0.366064 21.468201 78.269747
                                  Shree vaidyam ayurved panchkarma Clinic complementary_and_alternative_medicine                               {'primary': 'naturopathic_medicine', 'hierarchy': ['health_care', 'outpatient_care_facility', 'complementary_and_alternative_medicine', 'naturopathic_medicine'], 'alternates': None}    0.287458 21.468927 78.268850
                                                         Chambole Alankar                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.411425 21.469385 78.268893
                                                             Sayali Metal                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.517452 21.469383 78.268895
                                              BRAND Mens Collection Warud              fashion_and_apparel_store                                                             {'primary': 'mens_clothing_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'clothing_store', 'mens_clothing_store'], 'alternates': None}    0.652532 21.469456 78.269082
                                                                 Art Zone                       printing_service                                                                                                     {'primary': 'printing_service', 'hierarchy': ['services_and_business', 'printing_service'], 'alternates': None}    0.185143 21.469649 78.269810
                                                  Bajaj Finserv Gold Loan              fashion_and_apparel_store                                                                                           {'primary': 'jewelry_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'jewelry_store'], 'alternates': None}    0.850000 21.467522 78.271736
                                  Doctor S Deshmukh Jagrut Primary School                              education                                                                                                                                            {'primary': 'education', 'hierarchy': ['education'], 'alternates': None}    0.395698 21.468869 78.272435
                                                                Sai tiles         hardware_home_and_garden_store                                                             {'primary': 'home_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'home_goods_store'], 'alternates': None}    0.453960 21.469602 78.272498
                                                         Paragon Footwear              fashion_and_apparel_store                                                                                                 {'primary': 'shoe_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'shoe_store'], 'alternates': None}    0.770000 21.472766 78.273040
                                                    Sahajivan Social Club            social_or_community_service                                                                            {'primary': 'social_or_community_service', 'hierarchy': ['community_and_government', 'social_or_community_service'], 'alternates': None}    0.200603 21.473991 78.275921
                                             Malode Bichayat and Caterers                 event_or_party_service                                                                                             {'primary': 'caterer', 'hierarchy': ['services_and_business', 'event_or_party_service', 'caterer'], 'alternates': None}    0.596224 21.473773 78.273010
                                Shri Vishwayan Ayurveda Panchkarma Clinic     behavioral_or_mental_health_clinic                             {'primary': 'family_counseling', 'hierarchy': ['health_care', 'outpatient_care_facility', 'behavioral_or_mental_health_clinic', 'counseling', 'family_counseling'], 'alternates': None}    0.573966 21.474690 78.272070
                                              Veera Mobile and Electronic                      electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.253770 21.472403 78.271169
                                                      Hindustan Petroleum                            gas_station                                                                                        {'primary': 'gas_station', 'hierarchy': ['travel_and_transportation', 'fueling_station', 'gas_station'], 'alternates': None}    0.954000 21.472741 78.269711
                                                Shree Sant Gajanan Market                food_and_beverage_store                                                                                             {'primary': 'grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store'], 'alternates': None}    0.524635 21.471628 78.269561
                                                      National Men's Wear              fashion_and_apparel_store                                                                                         {'primary': 'clothing_store', 'hierarchy': ['shopping', 'fashion_and_apparel_store', 'clothing_store'], 'alternates': None}    0.184690 21.471812 78.268893
                                                     Saraswati Book Depot            books_music_and_video_store                                                                              {'primary': 'bookstore', 'hierarchy': ['shopping', 'specialty_store', 'books_music_and_video_store', 'bookstore'], 'alternates': None}    0.483612 21.471892 78.268881
                                 Shri Gajanan Hardware and Plywood Centre         hardware_home_and_garden_store                                                                 {'primary': 'hardware_store', 'hierarchy': ['shopping', 'specialty_store', 'hardware_home_and_garden_store', 'hardware_store'], 'alternates': None}    0.324062 21.472674 78.269201
                                  Shri Gurudev krushi kendra Rajura bazar                            b2b_service                                                                     {'primary': 'agriculture', 'hierarchy': ['services_and_business', 'b2b_service', 'b2b_agriculture_service', 'agriculture'], 'alternates': None}    0.558234 21.473560 78.269290
                                                  Patanjali Arogya Kendra                food_and_beverage_store                                                              {'primary': 'indian_grocery_store', 'hierarchy': ['shopping', 'food_and_beverage_store', 'grocery_store', 'indian_grocery_store'], 'alternates': None}    0.850000 21.473712 78.269693
                                                         Hanifa Furniture                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.289267 21.474363 78.270463
                                                            Patel traders                           manufacturer                                                                                              {'primary': 'manufacturer', 'hierarchy': ['services_and_business', 'b2b_service', 'manufacturer'], 'alternates': None}    0.410479 21.474502 78.270448
                             Belsare Multi Speciality Homoeopathic Clinic               outpatient_care_facility                                                                                               {'primary': 'outpatient_care_facility', 'hierarchy': ['health_care', 'outpatient_care_facility'], 'alternates': None}    0.382472 21.474568 78.270340
                                                          SS Mobile Warud                      electronics_store                                                                      {'primary': 'mobile_phone_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'mobile_phone_store'], 'alternates': None}    0.327947 21.474800 78.269740
                                                     Shivam Sports, warud                   sporting_goods_store                                                                                       {'primary': 'sporting_goods_store', 'hierarchy': ['shopping', 'specialty_store', 'sporting_goods_store'], 'alternates': None}    0.570937 21.474907 78.269480
                                                    New Ambika Collection                               shopping                                                                                                                                              {'primary': 'shopping', 'hierarchy': ['shopping'], 'alternates': None}    0.613389 21.474553 78.269570
                                                                  Lapcare                      electronics_store                                                                              {'primary': 'computer_store', 'hierarchy': ['shopping', 'specialty_store', 'electronics_store', 'computer_store'], 'alternates': None}    0.850000 21.475882 78.268832
                                                                IndianOil                            gas_station                                                                                        {'primary': 'gas_station', 'hierarchy': ['travel_and_transportation', 'fueling_station', 'gas_station'], 'alternates': None}    0.471639 21.476124 78.269464

In [38]:
def get_primary_taxonomy(x):
    if isinstance(x, dict):
        return x.get("primary")
    return None

gdf_clean["taxonomy_primary"] = gdf_clean["taxonomy"].apply(
    get_primary_taxonomy
)

print(gdf_clean["taxonomy_primary"].value_counts(dropna=False))

taxonomy_primary
hospital                    12
shopping                     9
None                         7
hotel                        6
restaurant                   6
                            ..
lodging                      1
indian_grocery_store         1
outpatient_care_facility     1
sporting_goods_store         1
religious_organization       1
Name: count, Length: 86, dtype: int64

In [39]:
def map_business_group(row):
    basic = str(row["basic_category"]).lower()
    primary = str(row["taxonomy_primary"]).lower()

    text = basic + " " + primary

    # Finance
    if any(x in text for x in [
        "bank", "finance", "credit", "loan", "atm", "insurance"
    ]):
        return "finance"

    # Healthcare
    if any(x in text for x in [
        "health", "medical", "clinic", "pharmacy",
        "medicine", "doctor", "hospital", "naturopathic",
        "outpatient", "counseling"
    ]):
        return "healthcare"

    # Agriculture
    if any(x in text for x in [
        "agriculture", "agricultural", "farm",
        "dairy", "fertilizer", "seed", "krushi"
    ]):
        return "agriculture"

    # Food & Grocery
    if any(x in text for x in [
        "grocery", "food", "restaurant", "cafe",
        "bakery", "sweet", "food_and_beverage"
    ]):
        return "food_and_grocery"

    # Automotive
    if any(x in text for x in [
        "auto", "automotive", "vehicle", "motorcycle",
        "car", "tyre", "repair"
    ]):
        return "automotive"

    # Retail
    if any(x in text for x in [
        "shopping", "store", "shop", "retail",
        "clothing", "fashion", "jewelry", "shoe",
        "hardware", "furniture", "electronics",
        "mobile", "bookstore"
    ]):
        return "retail"

    # Education
    if any(x in text for x in [
        "education", "school", "college",
        "educational", "training"
    ]):
        return "education"

    # Hospitality
    if any(x in text for x in [
        "hotel", "lodging", "lodge", "hospitality"
    ]):
        return "hospitality"

    # Services
    if any(x in text for x in [
        "service", "printing", "real_estate",
        "advertising", "marketing", "caterer",
        "party_and_event"
    ]):
        return "services"

    # Transport
    if any(x in text for x in [
        "transport", "bus", "train", "station",
        "gas_station", "fueling"
    ]):
        return "transport"

    # Entertainment / sports
    if any(x in text for x in [
        "movie", "theater", "gym", "sports",
        "sporting"
    ]):
        return "entertainment_sports"

    # Government / community
    if any(x in text for x in [
        "police", "government", "community",
        "social"
    ]):
        return "government_community"

    # Religious
    if any(x in text for x in [
        "temple", "hindu_place_of_worship",
        "religious", "mosque", "church"
    ]):
        return "religious"

    return "other"

In [40]:
gdf_clean["business_group"] = gdf_clean.apply(
    map_business_group,
    axis=1
)

print(gdf_clean["business_group"].value_counts())

business_group
retail                  35
services                25
healthcare              24
food_and_grocery        20
education               18
finance                 18
automotive              15
other                   11
transport                9
hospitality              8
agriculture              6
religious                5
entertainment_sports     3
government_community     3
Name: count, dtype: int64

In [41]:
gdf_final = gdf_clean[
    gdf_clean["confidence"] >= 0.5
].copy()

In [42]:
print("Final records:", len(gdf_final))
print(gdf_final["business_group"].value_counts())

Final records: 139
business_group
retail                  22
healthcare              18
finance                 18
food_and_grocery        16
services                13
education               10
automotive              10
hospitality              8
other                    7
transport                5
agriculture              4
religious                3
entertainment_sports     3
government_community     2
Name: count, dtype: int64

In [43]:
other_businesses = gdf_final[
    gdf_final["business_group"] == "other"
][
    ["business_name",
     "basic_category",
     "taxonomy_primary",
     "confidence",
     "lat",
     "lon"]
]

other_businesses

,business_name,basic_category,taxonomy_primary,confidence,lat,lon
65,"Californiya Cricket Academy, Warud",sport_league,None,0.696841,21.469600,78.272900
111,GMart Warud,None,None,0.714257,21.476046,78.270002
123,Exide Care - V.K. Trading Co,None,None,0.965500,21.476280,78.271684
127,Exide Care - Anand Motors,manufacturer,industrial_equipment_manufacturer,0.965500,21.476000,78.271001
160,Zunja,nature_reserve,nature_reserve,0.580611,21.476780,78.267830
163,Taro Pumps - Sanjay Electricals,None,None,0.603940,21.476780,78.267830
174,SMFG India Credit Co. Limited - Warud (Branch),None,None,0.850000,21.477891,78.258091

In [44]:
corrections = {
    "Californiya Cricket Academy, Warud": "entertainment_sports",
    "GMart Warud": "retail",
    "Exide Care - V.K. Trading Co": "automotive",
    "Exide Care - Anand Motors": "automotive",
    "Zunja": "other",
    "Taro Pumps - Sanjay Electricals": "agriculture",
    "SMFG India Credit Co. Limited - Warud (Branch)": "finance"
}

gdf_final["business_group"] = (
    gdf_final["business_name"]
    .map(corrections)
    .fillna(gdf_final["business_group"])
)

In [45]:
print("Final records:", len(gdf_final))
print(gdf_final["business_group"].value_counts())

Final records: 139
business_group
retail                  23
finance                 19
healthcare              18
food_and_grocery        16
services                13
automotive              12
education               10
hospitality              8
transport                5
agriculture              5
entertainment_sports     4
religious                3
government_community     2
other                    1
Name: count, dtype: int64

In [46]:
gdf_final[gdf_final["business_group"] == "other"][
    ["business_name", "basic_category", "taxonomy_primary"]
]

    business_name  basic_category taxonomy_primary
160         Zunja  nature_reserve   nature_reserve

In [47]:
# Mark whether a POI should be considered a competitor
gdf_final["is_competitor"] = (
    gdf_final["business_group"] != "other"
)

print("Total POIs:", len(gdf_final))
print("Competitor candidates:", gdf_final["is_competitor"].sum())
print("Context/non-competitor:", (~gdf_final["is_competitor"]).sum())

Total POIs: 139
Competitor candidates: 138
Context/non-competitor: 1

In [48]:
gdf_final[
    gdf_final["is_competitor"] == False
][
    ["business_name", "basic_category", "taxonomy_primary", "business_group"]
]

    business_name  basic_category taxonomy_primary business_group
160         Zunja  nature_reserve   nature_reserve          other

In [49]:
# Create final competitor dataset
competitors = gdf_final[
    gdf_final["is_competitor"] == True
].copy()

print("Competitor records:", len(competitors))

Competitor records: 138

In [50]:
competitors.to_file(
    "warud_competitors.geojson",
    driver="GeoJSON"
)

print("Saved successfully!")

Saved successfully!

In [51]:
competitors[
    [
        "business_name",
        "business_group",
        "basic_category",
        "taxonomy_primary",
        "confidence",
        "lat",
        "lon"
    ]
].to_csv(
    "warud_competitors.csv",
    index=False
)

print("CSV saved successfully!")

CSV saved successfully!

In [52]:
print("Records:", len(competitors))
print("CRS:", competitors.crs)
print("Geometry:", competitors.geometry.geom_type.value_counts())

Records: 138
CRS: EPSG:4326
Geometry: Point    138
Name: count, dtype: int64

In [53]:
!pip install sqlalchemy 
psycopg2-binary geoalchemy2

SyntaxError: invalid syntax (3461655193.py, line 2)

In [54]:
!pip install sqlalchemy psycopg2-binary geoalchemy2

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Collecting geoalchemy2
  Downloading geoalchemy2-0.20.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\lib\site-packages (from geoalchemy2) (25.0)
Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.8 MB 3.8 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.8 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.7 MB/s  0:00:00
Downloading geoalchemy2-0.20.0-py3-none-any.whl (96 kB)
Installing collected packages: psycopg2-binary, geoalchemy2

   -------------------- ------------------- 1/2 [geoalchemy2]
   -------------------- ------------------- 1/2 [geoalchemy2]
   ---------------------------------------- 2/2 [geoalchemy2]

Successfully installed geoalchemy2-0.20.0 psycopg2-binary-2.9.13

In [3]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Drama999@localhost:5432/udyam360"
)

print("Connection object created successfully")

Connection object created successfully

In [4]:
with engine.connect() as connection:
    print("Connected to PostgreSQL successfully!")

Connected to PostgreSQL successfully!

In [5]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
        CREATE TABLE IF NOT EXISTS competitors (
            id SERIAL PRIMARY KEY,
            business_name TEXT,
            business_group TEXT,
            basic_category TEXT,
            taxonomy_primary TEXT,
            confidence DOUBLE PRECISION,
            lat DOUBLE PRECISION,
            lon DOUBLE PRECISION,
            geom GEOMETRY(Point, 4326)
        );
    """))

print("competitors table created successfully!")

competitors table created successfully!

In [6]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_name = 'competitors';
    """))

    print(result.fetchall())

[('competitors',)]

In [7]:
from sqlalchemy import text

# Select only the columns we need
upload_df = competitors[
    [
        "business_name",
        "business_group",
        "basic_category",
        "taxonomy_primary",
        "confidence",
        "lat",
        "lon"
    ]
].copy()

# Insert records
upload_df.to_sql(
    "competitors",
    engine,
    if_exists="append",
    index=False
)

print("138 competitor records inserted!")

NameError: name 'competitors' is not defined

In [8]:
with engine.begin() as connection:
    connection.execute(text("""
        UPDATE competitors
        SET geom = ST_SetSRID(
            ST_MakePoint(lon, lat),
            4326
        );
    """))

print("PostGIS geometry created successfully!")

PostGIS geometry created successfully!

In [9]:
with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            COUNT(*) AS total_records,
            COUNT(geom) AS records_with_geometry
        FROM competitors;
    """))

    print(result.fetchall())

[(138, 138)]

In [10]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS competitors_geom_gix
        ON competitors
        USING GIST (geom);
    """))

print("Spatial index created successfully!")

Spatial index created successfully!

In [11]:
from sqlalchemy import text

warud_lat = 21.4710
warud_lon = 78.2690
radius_m = 1000

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            business_name,
            business_group,
            ROUND(
                ST_Distance(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography
                )::numeric,
                2
            ) AS distance_m
        FROM competitors
        WHERE ST_DWithin(
            geom::geography,
            ST_SetSRID(
                ST_MakePoint(:lon, :lat),
                4326
            )::geography,
            :radius_m
        )
        ORDER BY distance_m;
    """), {
        "lat": warud_lat,
        "lon": warud_lon,
        "radius_m": radius_m
    })

    rows = result.fetchall()

print(f"Competitors within {radius_m/1000:.0f} km:", len(rows))

for row in rows[:10]:
    print(row)

Competitors within 1 km: 117
('Vidarbha Hardware', 'retail', Decimal('48.35'))
('Srad Deshmukh Hospital', 'healthcare', Decimal('70.52'))
('Shree Sant Gajanan Market', 'food_and_grocery', Decimal('90.65'))
('Takarkhede Automotive E-Bike Pandhurna Chwok Warud 444906 ', 'automotive', Decimal('126.14'))
('Shriram Finance Limited', 'finance', Decimal('133.81'))
('ICICI Bank', 'finance', Decimal('137.83'))
('Warud', 'hospitality', Decimal('143.70'))
('Jain Cold Drinks and Sweets', 'retail', Decimal('165.27'))
('BRAND Mens Collection Warud', 'retail', Decimal('171.17'))
('Sayali Metal', 'retail', Decimal('179.41'))

In [12]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            business_group,
            COUNT(*) AS competitor_count
        FROM competitors
        WHERE ST_DWithin(
            geom::geography,
            ST_SetSRID(
                ST_MakePoint(:lon, :lat),
                4326
            )::geography,
            :radius_m
        )
        GROUP BY business_group
        ORDER BY competitor_count DESC;
    """), {
        "lat": warud_lat,
        "lon": warud_lon,
        "radius_m": 1000
    })

    category_counts = result.fetchall()

print("Competitors by category within 1 km:\n")

for category, count in category_counts:
    print(f"{category}: {count}")

Competitors by category within 1 km:

retail: 22
healthcare: 17
finance: 16
food_and_grocery: 14
services: 13
automotive: 9
hospitality: 8
education: 7
agriculture: 5
entertainment_sports: 4
transport: 1
government_community: 1

In [13]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            radius_km,
            COUNT(*) AS total_competitors
        FROM (
            SELECT
                1 AS radius_km
            FROM competitors
            WHERE ST_DWithin(
                geom::geography,
                ST_SetSRID(
                    ST_MakePoint(:lon, :lat),
                    4326
                )::geography,
                1000
            )

            UNION ALL

            SELECT
                3 AS radius_km
            FROM competitors
            WHERE ST_DWithin(
                geom::geography,
                ST_SetSRID(
                    ST_MakePoint(:lon, :lat),
                    4326
                )::geography,
                3000
            )

            UNION ALL

            SELECT
                5 AS radius_km
            FROM competitors
            WHERE ST_DWithin(
                geom::geography,
                ST_SetSRID(
                    ST_MakePoint(:lon, :lat),
                    4326
                )::geography,
                5000
            )
        ) x
        GROUP BY radius_km
        ORDER BY radius_km;
    """), {
        "lat": warud_lat,
        "lon": warud_lon
    })

    for row in result:
        print(f"{row[0]} km → {row[1]} competitors")

1 km → 117 competitors
3 km → 132 competitors
5 km → 137 competitors

In [14]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            business_group,
            COUNT(*) FILTER (
                WHERE ST_DWithin(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography,
                    1000
                )
            ) AS within_1km,

            COUNT(*) FILTER (
                WHERE ST_DWithin(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography,
                    3000
                )
            ) AS within_3km,

            COUNT(*) FILTER (
                WHERE ST_DWithin(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography,
                    5000
                )
            ) AS within_5km

        FROM competitors
        GROUP BY business_group
        ORDER BY within_1km DESC;
    """), {
        "lat": warud_lat,
        "lon": warud_lon
    })

    rows = result.fetchall()

print("Category-wise competitor density:\n")

for row in rows:
    print(
        f"{row[0]:25} "
        f"1 km: {row[1]:3} | "
        f"3 km: {row[2]:3} | "
        f"5 km: {row[3]:3}"
    )

Category-wise competitor density:

retail                    1 km:  22 | 3 km:  23 | 5 km:  23
healthcare                1 km:  17 | 3 km:  18 | 5 km:  18
finance                   1 km:  16 | 3 km:  19 | 5 km:  19
food_and_grocery          1 km:  14 | 3 km:  15 | 5 km:  16
services                  1 km:  13 | 3 km:  13 | 5 km:  13
automotive                1 km:   9 | 3 km:  10 | 5 km:  11
hospitality               1 km:   8 | 3 km:   8 | 5 km:   8
education                 1 km:   7 | 3 km:   9 | 5 km:  10
agriculture               1 km:   5 | 3 km:   5 | 5 km:   5
entertainment_sports      1 km:   4 | 3 km:   4 | 5 km:   4
transport                 1 km:   1 | 3 km:   4 | 5 km:   5
government_community      1 km:   1 | 3 km:   1 | 5 km:   2
religious                 1 km:   0 | 3 km:   3 | 5 km:   3

In [15]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            business_name,
            business_group,
            ROUND(
                ST_Distance(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography
                )::numeric,
                2
            ) AS distance_m
        FROM competitors
        ORDER BY distance_m
        LIMIT 10;
    """), {
        "lat": warud_lat,
        "lon": warud_lon
    })

    rows = result.fetchall()

print("10 nearest competitors:\n")

for i, row in enumerate(rows, start=1):
    print(
        f"{i}. {row[0]} | "
        f"{row[1]} | "
        f"{row[2]} m"
    )

10 nearest competitors:

1. Vidarbha Hardware | retail | 48.35 m
2. Srad Deshmukh Hospital | healthcare | 70.52 m
3. Shree Sant Gajanan Market | food_and_grocery | 90.65 m
4. Takarkhede Automotive E-Bike Pandhurna Chwok Warud 444906  | automotive | 126.14 m
5. Shriram Finance Limited | finance | 133.81 m
6. ICICI Bank | finance | 137.83 m
7. Warud | hospitality | 143.70 m
8. Jain Cold Drinks and Sweets | retail | 165.27 m
9. BRAND Mens Collection Warud | retail | 171.17 m
10. Sayali Metal | retail | 179.41 m

In [16]:
!pip install folium

Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in c:\users\hp\anaconda3\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from folium) (2.3.5)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from folium) (2.32.5)
Requirement already satisfied: xyzservices in c:\users\hp\anaconda3\lib\site-packages (from folium) (2025.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests->folium) (2025.11.12)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Installing collected packages: branca, folium

   -------------------- ------------------- 1/2 [folium]
   ---------------------------------------- 2/2 [folium]

Successfully installed branca-0.8.2 folium-0.20.0

In [17]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import text

with engine.connect() as connection:
    df_map = pd.read_sql(
        text("""
            SELECT
                business_name,
                business_group,
                basic_category,
                confidence,
                lat,
                lon
            FROM competitors
        """),
        connection
    )

print("Competitors loaded:", len(df_map))
df_map.head()

Competitors loaded: 138

,business_name,business_group,basic_category,confidence,lat,lon
0,Genericart Medicine Store,healthcare,pharmacy_and_drug_store,0.770000,21.471210,78.264701
1,Shradha Auto Services - Hero MotoCorp,retail,shopping,0.965500,21.471210,78.264700
2,Bajaj Finance Branch,finance,bank_or_credit_union,0.850000,21.471210,78.264700
3,Jain Cold Drinks and Sweets,retail,casual_eatery,0.568382,21.472436,78.268566
4,Nature's Pride,services,real_estate_service,0.527956,21.471690,78.267400

In [18]:
import folium

m = folium.Map(
    location=[warud_lat, warud_lon],
    zoom_start=14
)

# Proposed / selected location
folium.Marker(
    [warud_lat, warud_lon],
    popup="Selected Location",
    tooltip="Selected Location",
    icon=folium.Icon(color="red", icon="star")
).add_to(m)

# Competitor locations
for _, row in df_map.iterrows():

    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=5,
        popup=(
            f"<b>{row['business_name']}</b><br>"
            f"Category: {row['business_group']}<br>"
            f"Confidence: {row['confidence']:.2f}"
        ),
        tooltip=row["business_name"],
        fill=True
    ).add_to(m)

m

In [19]:
import folium

m = folium.Map(
    location=[warud_lat, warud_lon],
    zoom_start=14
)

# Proposed / selected location
folium.Marker(
    [warud_lat, warud_lon],
    popup="Selected Location",
    tooltip="Selected Location",
    icon=folium.Icon(color="red", icon="star")
).add_to(m)

# Competitor locations
for _, row in df_map.iterrows():

    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=5,
        popup=(
            f"<b>{row['business_name']}</b><br>"
            f"Category: {row['business_group']}<br>"
            f"Confidence: {row['confidence']:.2f}"
        ),
        tooltip=row["business_name"],
        fill=True
    ).add_to(m)

m

In [20]:
import folium
from sqlalchemy import text
import pandas as pd

selected_category = "retail"

with engine.connect() as connection:
    df_map = pd.read_sql(
        text("""
            SELECT
                business_name,
                business_group,
                confidence,
                lat,
                lon
            FROM competitors
            WHERE business_group = :category
        """),
        connection,
        params={"category": selected_category}
    )

print(f"{selected_category} competitors:", len(df_map))

retail competitors: 23

In [21]:
m = folium.Map(
    location=[warud_lat, warud_lon],
    zoom_start=14
)

# Selected/proposed business location
folium.Marker(
    [warud_lat, warud_lon],
    popup="Proposed Business Location",
    tooltip="Your Business",
    icon=folium.Icon(color="red", icon="star")
).add_to(m)

# Same-category competitors only
for _, row in df_map.iterrows():

    folium.CircleMarker(
        location=[row["lat"], row["lon"]],
        radius=6,
        popup=(
            f"<b>{row['business_name']}</b><br>"
            f"Category: {row['business_group']}<br>"
            f"Confidence: {row['confidence']:.2f}"
        ),
        tooltip=row["business_name"],
        fill=True
    ).add_to(m)

m

In [28]:
# Add radius circles around the proposed location

folium.Circle(
    location=[warud_lat, warud_lon],
    radius=1000,
    fill=False,
    popup="1 km Competition Radius"
).add_to(m)

folium.Circle(
    location=[warud_lat, warud_lon],
    radius=3000,
    fill=False,
    popup="3 km Competition Radius"
).add_to(m)

folium.Circle(
    location=[warud_lat, warud_lon],
    radius=5000,
    fill=False,
    popup="5 km Competition Radius"
).add_to(m)

m

In [27]:
# Add only 1 km competition radius

folium.Circle(
    location=[warud_lat, warud_lon],
    radius=1000,   # 1000 metres = 1 km
    fill=False,
    popup="1 km Same-Category Competition Radius"
).add_to(m)

m

In [29]:
folium.Marker(
    location=[warud_lat, warud_lon],
    popup="<b>Proposed Business Location</b>",
    tooltip="⭐ Your Business",
    icon=folium.Icon(
        color="red",
        icon="home",
        prefix="fa"
    )
).add_to(m)


m

In [30]:
import numpy as np
import geopandas as gpd
from shapely.geometry import box

# Get competitor coordinates
with engine.connect() as connection:
    df_points = pd.read_sql(
        text("""
            SELECT
                business_name,
                business_group,
                lat,
                lon
            FROM competitors
            WHERE business_group = :category
        """),
        connection,
        params={"category": selected_category}
    )

# Convert to GeoDataFrame
gdf_points = gpd.GeoDataFrame(
    df_points,
    geometry=gpd.points_from_xy(
        df_points["lon"],
        df_points["lat"]
    ),
    crs="EPSG:4326"
)

print("Competitors:", len(gdf_points))

Competitors: 23

In [31]:
# Get bounding box of competitor area
minx, miny, maxx, maxy = gdf_points.total_bounds

# Grid cell size in degrees
cell_size = 0.005

grid = []

x = minx
while x < maxx:
    y = miny

    while y < maxy:
        grid.append(
            box(
                x,
                y,
                x + cell_size,
                y + cell_size
            )
        )
        y += cell_size

    x += cell_size

grid_gdf = gpd.GeoDataFrame(
    {"geometry": grid},
    crs="EPSG:4326"
)

print("Grid cells:", len(grid_gdf))

Grid cells: 6

In [32]:
joined = gpd.sjoin(
    gdf_points,
    grid_gdf,
    predicate="within",
    how="left"
)

density = (
    joined
    .groupby("index_right")
    .size()
    .rename("competitor_count")
)

grid_gdf["competitor_count"] = (
    density
    .reindex(grid_gdf.index)
    .fillna(0)
)

print(grid_gdf[["competitor_count"]].describe())

       competitor_count
count          6.000000
mean           3.500000
std            3.391165
min            1.000000
25%            1.250000
50%            2.500000
75%            3.750000
max           10.000000

In [33]:
print("Grid cells:", len(grid_gdf))

Grid cells: 6

In [34]:
print(grid_gdf[["competitor_count"]].describe())

       competitor_count
count          6.000000
mean           3.500000
std            3.391165
min            1.000000
25%            1.250000
50%            2.500000
75%            3.750000
max           10.000000

In [35]:
from shapely.geometry import box

# Get bounding box
minx, miny, maxx, maxy = gdf_points.total_bounds

# Smaller grid cells
cell_size = 0.001

grid = []

x = minx
while x < maxx:
    y = miny

    while y < maxy:
        grid.append(
            box(
                x,
                y,
                x + cell_size,
                y + cell_size
            )
        )
        y += cell_size

    x += cell_size

grid_gdf = gpd.GeoDataFrame(
    {"geometry": grid},
    crs="EPSG:4326"
)

print("Grid cells:", len(grid_gdf))

Grid cells: 140

In [36]:
joined = gpd.sjoin(
    gdf_points,
    grid_gdf,
    predicate="within",
    how="left"
)

density = (
    joined
    .groupby("index_right")
    .size()
    .rename("competitor_count")
)

grid_gdf["competitor_count"] = (
    density
    .reindex(grid_gdf.index)
    .fillna(0)
)

print(grid_gdf[["competitor_count"]].describe())

       competitor_count
count        140.000000
mean           0.150000
std            0.463409
min            0.000000
25%            0.000000
50%            0.000000
75%            0.000000
max            3.000000

In [37]:
print("Grid cells:", len(grid_gdf))
print(grid_gdf[["competitor_count"]].describe())

Grid cells: 140
       competitor_count
count        140.000000
mean           0.150000
std            0.463409
min            0.000000
25%            0.000000
50%            0.000000
75%            0.000000
max            3.000000

In [38]:
def classify_density(count):
    if count == 0:
        return "No Competition"
    elif count == 1:
        return "Low"
    elif count == 2:
        return "Medium"
    else:
        return "High"

grid_gdf["density_level"] = grid_gdf["competitor_count"].apply(
    classify_density
)

print(
    grid_gdf["density_level"].value_counts()
)

density_level
No Competition    124
Low                12
Medium              3
High                1
Name: count, dtype: int64

In [39]:
import folium

density_map = folium.Map(
    location=[warud_lat, warud_lon],
    zoom_start=14
)

# Add density grid
for _, row in grid_gdf.iterrows():

    level = row["density_level"]
    
    if level == "No Competition":
        fill_opacity = 0.05
    elif level == "Low":
        fill_opacity = 0.30
    elif level == "Medium":
        fill_opacity = 0.50
    else:
        fill_opacity = 0.75

    folium.GeoJson(
        row["geometry"],
        style_function=lambda feature, opacity=fill_opacity: {
            "fillOpacity": opacity,
            "weight": 1
        },
        tooltip=(
            f"Competition: {level}<br>"
            f"Competitors: {row['competitor_count']}"
        )
    ).add_to(density_map)

# Proposed business location
folium.Marker(
    location=[warud_lat, warud_lon],
    popup="<b>Proposed Business Location</b>",
    tooltip="Your Business"
).add_to(density_map)

density_map

In [40]:
def classify_density(count):
    if count == 0:
        return "No Competition"
    elif count == 1:
        return "Low"
    elif count == 2:
        return "Medium"
    else:
        return "High"

grid_gdf["density_level"] = grid_gdf["competitor_count"].apply(
    classify_density
)

print(grid_gdf["density_level"].value_counts())

density_level
No Competition    124
Low                12
Medium              3
High                1
Name: count, dtype: int64

In [41]:
density_map = folium.Map(
    location=[warud_lat, warud_lon],
    zoom_start=14
)

for _, row in grid_gdf.iterrows():

    level = row["density_level"]

    if level == "No Competition":
        fill_opacity = 0.05
    elif level == "Low":
        fill_opacity = 0.30
    elif level == "Medium":
        fill_opacity = 0.50
    else:
        fill_opacity = 0.75

    folium.GeoJson(
        row["geometry"],
        style_function=lambda feature, opacity=fill_opacity: {
            "fillOpacity": opacity,
            "weight": 1
        },
        tooltip=(
            f"Competition: {level}<br>"
            f"Competitors: {row['competitor_count']}"
        )
    ).add_to(density_map)

# Proposed business
folium.Marker(
    location=[warud_lat, warud_lon],
    popup="<b>Proposed Business Location</b>",
    tooltip="Your Business"
).add_to(density_map)

density_map

In [42]:
selected_category = "retail"
radius_m = 1000

with engine.connect() as connection:
    result = connection.execute(text("""
        SELECT
            business_name,
            business_group,
            ROUND(
                ST_Distance(
                    geom::geography,
                    ST_SetSRID(
                        ST_MakePoint(:lon, :lat),
                        4326
                    )::geography
                )::numeric,
                2
            ) AS distance_m
        FROM competitors
        WHERE business_group = :category
          AND ST_DWithin(
              geom::geography,
              ST_SetSRID(
                  ST_MakePoint(:lon, :lat),
                  4326
              )::geography,
              :radius_m
          )
        ORDER BY distance_m;
    """), {
        "lat": warud_lat,
        "lon": warud_lon,
        "category": selected_category,
        "radius_m": radius_m
    })

    rows = result.fetchall()

print("Category:", selected_category)
print("Competitors found:", len(rows))

for row in rows[:10]:
    print(row)

Category: retail
Competitors found: 22
('Vidarbha Hardware', 'retail', Decimal('48.35'))
('Jain Cold Drinks and Sweets', 'retail', Decimal('165.27'))
('BRAND Mens Collection Warud', 'retail', Decimal('171.17'))
('Sayali Metal', 'retail', Decimal('179.41'))
('New Ambika Collection', 'retail', Decimal('397.84'))
('Shrikant Jewellers', 'retail', Decimal('418.03'))
('Shivam Sports, warud', 'retail', Decimal('435.50'))
('TRENDS', 'retail', Decimal('446.22'))
('Shradha Auto Services - Hero MotoCorp', 'retail', Decimal('446.26'))
('Paragon Footwear', 'retail', Decimal('462.14'))

In [43]:
!pip install fastapi uvicorn

Collecting fastapi
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn
  Downloading uvicorn-0.53.0-py3-none-any.whl.metadata (6.6 kB)
Collecting starlette>=0.46.0 (from fastapi)
  Downloading starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: pydantic>=2.9.0 in c:\users\hp\anaconda3\lib\site-packages (from fastapi) (2.12.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\hp\anaconda3\lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp\anaconda3\lib\site-packages (from fastapi) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: click>=7.0 in c:\users\hp\anaconda3\lib\site-packages (from uvicorn) (8.5.0)
Requirement already satisfied: h11>=0.8 in c:\users\hp\anaconda3\lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp\anaconda3\lib\site-packages (from pydantic>=2.9.0->fastapi) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\hp\anaconda3\lib\site-packages (from pydantic>=2.9.0->fastapi) (2.41.5)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\hp\anaconda3\lib\site-packages (from starlette>=0.46.0->fastapi) (4.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\hp\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.11)
Requirement already satisfied: sniffio>=1.1 in c:\users\hp\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)
Downloading uvicorn-0.53.0-py3-none-any.whl (87 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading starlette-1.6.0-py3-none-any.whl (75 kB)
Installing collected packages: uvicorn, annotated-doc, starlette, fastapi

   ---------------------------------------- 0/4 [uvicorn]
   ---------- ----------------------------- 1/4 [annotated-doc]
   -------------------- ------------------- 2/4 [starlette]
   ------------------------------ --------- 3/4 [fastapi]
   ------------------------------ --------- 3/4 [fastapi]
   ---------------------------------------- 4/4 [fastapi]

Successfully installed annotated-doc-0.0.5 fastapi-0.141.1 starlette-1.6.0 uvicorn-0.53.0